selectors: ".node\r\n.field--name-body\r\n.youtube-container\r\n.field--name-field-media-oembed-video"
custom_vendors: ''
ignore_selectors: ''
_core:
  default_config_hash: 2VIFfYIzLIphEpkJSH9KfhEE0P66ieHfusDj6QMJIzY
