_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
smtp_on: true
smtp_host: mail.livekaraokeband.co.uk
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: info@livekaraokeband.co.uk
smtp_password: 'nE4MR#F4'
smtp_from: info@livekaraokeband.co.uk
smtp_fromname: 'The Live Karaoke Band'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: ali@alimartin.com
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
